In [1]:
import pandas as pd 
import numpy as np

In [2]:
df_2021 = pd.read_csv('Dataset/Dataset - Sécurité Routière.xlsx - caract 2021.csv', sep=';')
df_2022 = pd.read_csv('Dataset/Dataset - Sécurité Routière.xlsx - caract 2022.csv', sep=';')
df_2023 = pd.read_csv('Dataset/Dataset - Sécurité Routière.xlsx - caract 2023.csv', sep=';')
df_2024 = pd.read_csv('Dataset/Dataset - Sécurité Routière.xlsx - caract 2024.csv', sep=',')

# Now concatenate
caract_df = pd.concat([df_2024, df_2023, df_2022, df_2021], ignore_index=True)

print(caract_df.head())

        Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  col  \
0  2.024000e+11    25     3  2024   7:40    2  70  70285    1    1    5    1
1  2.024000e+11    20     3  2024  15:05    1  21  21054    2    3    7    6
2  2.024000e+11    22     3  2024  19:30    2  15  15012    1    1    1    6
3  2.024000e+11    24     3  2024  17:50    1  14  14118    2    3    7    3
4  2.024000e+11    25     3  2024  19:35    5  13  13106    1    3    2    5

                      adr        lat      long  Accident_Id
0                    D438   47.56277   6.75832          NaN
1  HOTEL DIEU (RUE DE L')   47.02109   4.83755          NaN
2      Allée des Tilleuls  44.902384  2.496418          NaN
3        128 Rue d'Authie   49.19166  -0.39851          NaN
4  BEDOULE (CHEMIN DE LA)      43.39      5.35          NaN

In [3]:
caract_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221044 entries, 0 to 221043
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Num_Acc      165742 non-null  float64
 1   jour         221044 non-null  int64
 2   mois         221044 non-null  int64
 3   an           221044 non-null  int64
 4   hrmn         221044 non-null  object
 5   lum          221044 non-null  int64
 6   dep          221044 non-null  object
 7   com          221044 non-null  object
 8   agg          221044 non-null  int64
 9   int          221044 non-null  int64
 10  atm          221044 non-null  int64
 11  col          221044 non-null  int64
 12  adr          215539 non-null  object
 13  lat          221044 non-null  object
 14  long         221044 non-null  object
 15  Accident_Id  55302 non-null   float64
dtypes: float64(2), int64(8), object(6)
memory usage: 27.0+ MB

In [4]:
h_fix = caract_df['hrmn'].astype(str).str.replace(':', '').str.replace('nan', '0000').str.zfill(4)

date_string = (
    df_2024['an'].astype(str) + '-' + 
    df_2024['mois'].astype(str) + '-' + 
    df_2024['jour'].astype(str) + ' ' + 
    h_fix.str[:2] + ':' + h_fix.str[2:]
)

caract_df['date'] = pd.to_datetime(date_string, errors='coerce')

errors = caract_df['date'].isna().sum()
print(f"Nombre de dates invalides : {errors}")

caract_df = caract_df.drop(columns=['an', 'mois', 'jour', 'hrmn', 'adr'])

print(caract_df.head())

Nombre de dates invalides : 166642
        Num_Acc  lum dep    com  agg  int  atm  col        lat      long  \
0  2.024000e+11    2  70  70285    1    1    5    1   47.56277   6.75832
1  2.024000e+11    1  21  21054    2    3    7    6   47.02109   4.83755
2  2.024000e+11    2  15  15012    1    1    1    6  44.902384  2.496418
3  2.024000e+11    1  14  14118    2    3    7    3   49.19166  -0.39851
4  2.024000e+11    5  13  13106    1    3    2    5      43.39      5.35

   Accident_Id                date
0          NaN 2024-03-25 07:40:00
1          NaN 2024-03-20 15:05:00
2          NaN 2024-03-22 19:30:00
3          NaN 2024-03-24 17:50:00
4          NaN 2024-03-25 19:35:00

In [5]:
caract_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221044 entries, 0 to 221043
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Num_Acc      165742 non-null  float64
 1   lum          221044 non-null  int64
 2   dep          221044 non-null  object
 3   com          221044 non-null  object
 4   agg          221044 non-null  int64
 5   int          221044 non-null  int64
 6   atm          221044 non-null  int64
 7   col          221044 non-null  int64
 8   lat          221044 non-null  object
 9   long         221044 non-null  object
 10  Accident_Id  55302 non-null   float64
 11  date         54402 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(5), object(4)
memory usage: 20.2+ MB

In [6]:
caract_df = caract_df.drop(columns=['Accident_Id'])

In [7]:
caract_df = caract_df.drop(columns=['an', 'mois', 'jour', 'adr'])
print(caract_df.info())

KeyError: "['an', 'mois', 'jour', 'adr'] not found in axis"

In [8]:
caract_df

,Num_Acc,lum,dep,com,agg,int,atm,col,lat,long,date
0,2.024000e+11,2,70,70285,1,1,5,1,47.56277,6.75832,2024-03-25 07:40:00
1,2.024000e+11,1,21,21054,2,3,7,6,47.02109,4.83755,2024-03-20 15:05:00
2,2.024000e+11,2,15,15012,1,1,1,6,44.902384,2.496418,2024-03-22 19:30:00
3,2.024000e+11,1,14,14118,2,3,7,3,49.19166,-0.39851,2024-03-24 17:50:00
4,2.024000e+11,5,13,13106,1,3,2,5,43.39,5.35,2024-03-25 19:35:00
...,...,...,...,...,...,...,...,...,...,...,...
221039,2.021001e+11,3,33,33021,1,1,5,6,"44,5266190000","-0,1955440000",NaT
221040,2.021001e+11,1,38,38405,1,1,2,6,"45,3802910000","5,7049140000",NaT
221041,2.021001e+11,3,26,26064,1,1,2,1,"44,9112100000","5,0196360000",NaT
221042,2.021001e+11,1,33,33003,1,2,1,6,"44,9542747363","-0,5179211363",NaT
221043,2.021001e+11,3,78,78423,1,1,3,1,"48,7966700000","2,0505000000",NaT

In [9]:
nouveaux_noms = {
    'Num_ACC': 'luminosite',
    'dep': 'departement',
    'com': 'commune',
    'agg': 'agglomeration',
    'int': 'intersection',
    'atm': 'meteo',
    'col': 'type_collision'
}

# On applique le changement
caract_df = caract_df.rename(columns=nouveaux_noms)

# On vérifie le résultat
print(caract_df.columns)
caract_df.head()

Index(['Num_Acc', 'lum', 'departement', 'commune', 'agglomeration',
       'intersection', 'meteo', 'type_collision', 'lat', 'long', 'date'],
      dtype='object')

,Num_Acc,lum,departement,commune,agglomeration,intersection,meteo,type_collision,lat,long,date
0,2.024000e+11,2,70,70285,1,1,5,1,47.56277,6.75832,2024-03-25 07:40:00
1,2.024000e+11,1,21,21054,2,3,7,6,47.02109,4.83755,2024-03-20 15:05:00
2,2.024000e+11,2,15,15012,1,1,1,6,44.902384,2.496418,2024-03-22 19:30:00
3,2.024000e+11,1,14,14118,2,3,7,3,49.19166,-0.39851,2024-03-24 17:50:00
4,2.024000e+11,5,13,13106,1,3,2,5,43.39,5.35,2024-03-25 19:35:00

In [11]:
colonnes_a_traiter = ['meteo', 'type_collision']
caract_df[colonnes_a_traiter] = caract_df[colonnes_a_traiter].replace(-1, np.nan)
caract_df

,Num_Acc,lum,departement,commune,agglomeration,intersection,meteo,type_collision,lat,long,date
0,2.024000e+11,2,70,70285,1,1,5.0,1.0,47.56277,6.75832,2024-03-25 07:40:00
1,2.024000e+11,1,21,21054,2,3,7.0,6.0,47.02109,4.83755,2024-03-20 15:05:00
2,2.024000e+11,2,15,15012,1,1,1.0,6.0,44.902384,2.496418,2024-03-22 19:30:00
3,2.024000e+11,1,14,14118,2,3,7.0,3.0,49.19166,-0.39851,2024-03-24 17:50:00
4,2.024000e+11,5,13,13106,1,3,2.0,5.0,43.39,5.35,2024-03-25 19:35:00
...,...,...,...,...,...,...,...,...,...,...,...
221039,2.021001e+11,3,33,33021,1,1,5.0,6.0,"44,5266190000","-0,1955440000",NaT
221040,2.021001e+11,1,38,38405,1,1,2.0,6.0,"45,3802910000","5,7049140000",NaT
221041,2.021001e+11,3,26,26064,1,1,2.0,1.0,"44,9112100000","5,0196360000",NaT
221042,2.021001e+11,1,33,33003,1,2,1.0,6.0,"44,9542747363","-0,5179211363",NaT
221043,2.021001e+11,3,78,78423,1,1,3.0,1.0,"48,7966700000","2,0505000000",NaT

In [12]:
caract_df.to_csv('caract 2021-2024.csv', index=False, sep=';', encoding='utf-8')