In [1]:
import pandas as pd

In [11]:
df_vehicule = pd.read_csv(r"C:\Users\bsacu\Desktop\FullStack\Projet final\Python\projet-groupe-jedha\Dataset\Dataset - Sécurité Routière.xlsx - vehicules 2021.csv", sep=";")

In [12]:
df_vehicule.head()

,Num_Acc,id_vehicule,num_veh,senc,catv,obs,obsm,choc,manv,motor,occutc
0,202100000001,201 764,B01,1,1,0,2,1,1,5,NaN
1,202100000001,201 765,A01,1,7,0,9,3,17,1,NaN
2,202100000002,201 762,A01,0,7,2,2,1,1,0,NaN
3,202100000002,201 763,B01,0,7,0,2,1,9,0,NaN
4,202100000003,201 761,A01,1,7,0,1,3,1,1,NaN

In [49]:
# Chargement des deux premiers
df2021 = pd.read_csv('projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - vehicules 2021.csv', sep=';', encoding='latin-1', dtype=str)
df2022 = pd.read_csv('projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - vehicules 2022.csv', sep=';', encoding='latin-1', dtype=str)

# Nettoyage des noms de colonnes
df2021.columns = df2021.columns.str.strip().str.replace('"', '')
df2022.columns = df2022.columns.str.strip().str.replace('"', '')

# Tentative de fusion
fusion_1 = pd.concat([df2021, df2022], ignore_index=True)

print("--- TEST 1 : 2021 + 2022 ---")
print(f"Nombre de colonnes : {len(fusion_1.columns)}")
print(f"Colonnes : {list(fusion_1.columns)}")

--- TEST 1 : 2021 + 2022 ---
Nombre de colonnes : 11
Colonnes : ['Num_Acc', 'id_vehicule', 'num_veh', 'senc', 'catv', 'obs', 'obsm', 'choc', 'manv', 'motor', 'occutc']

In [50]:
df2023 = pd.read_csv('projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - vehicules 2023.csv', sep=';', encoding='latin-1', dtype=str)
df2023.columns = df2023.columns.str.strip().str.replace('"', '')

# On ajoute 2023 à notre première fusion
fusion_2 = pd.concat([fusion_1, df2023], ignore_index=True)

print("--- TEST 2 : Ajout de 2023 ---")
print(f"Nombre de colonnes : {len(fusion_2.columns)}")
print(f"Colonnes : {list(fusion_2.columns)}")

--- TEST 2 : Ajout de 2023 ---
Nombre de colonnes : 11
Colonnes : ['Num_Acc', 'id_vehicule', 'num_veh', 'senc', 'catv', 'obs', 'obsm', 'choc', 'manv', 'motor', 'occutc']

In [53]:
# On utilise la virgule ici comme tu l'as identifié
df2024 = pd.read_csv('projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - vehicules 2024.csv', sep=',', encoding='latin-1', dtype=str)
df2024.columns = df2024.columns.str.strip().str.replace('"', '')

# On ajoute 2024 à la fusion précédente
fusion_finale = pd.concat([fusion_2, df2024], ignore_index=True)

print("--- TEST 3 : Ajout de 2024 ---")
print(f"Nombre de colonnes : {len(fusion_finale.columns)}")
print(f"Colonnes : {list(fusion_finale.columns)}")

--- TEST 3 : Ajout de 2024 ---
Nombre de colonnes : 11
Colonnes : ['Num_Acc', 'id_vehicule', 'num_veh', 'senc', 'catv', 'obs', 'obsm', 'choc', 'manv', 'motor', 'occutc']

In [57]:
# Sauvegarde du résultat final avec le point-virgule comme standard
fusion_finale.to_csv('fusion_vehicules_21_24_OK.csv', index=False, sep=';')

print("Fichier sauvegardé avec succès sous le nom : fusion_vehicules_21_24_OK.csv")
print(f"Total final : {len(fusion_finale)} lignes et {len(fusion_finale.columns)} colonnes.")

Fichier sauvegardé avec succès sous le nom : fusion_vehicules_21_24_OK.csv
Total final : 378071 lignes et 11 colonnes.

In [58]:
fusion_finale

,Num_Acc,id_vehicule,num_veh,senc,catv,obs,obsm,choc,manv,motor,occutc
0,202100000001,201Â 764,B01,1,1,0,2,1,1,5,NaN
1,202100000001,201Â 765,A01,1,7,0,9,3,17,1,NaN
2,202100000002,201Â 762,A01,0,7,2,2,1,1,0,NaN
3,202100000002,201Â 763,B01,0,7,0,2,1,9,0,NaN
4,202100000003,201Â 761,A01,1,7,0,1,3,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
378066,202400054401,155 Â 686 Â 119,Y01,1,60,1,2,7,0,5,NaN
378067,202400054401,155 Â 686 Â 120,A01,1,33,1,2,1,1,1,NaN
378068,202400054402,155 Â 686 Â 118,A01,1,10,0,2,1,2,1,NaN
378069,202400054402,155 Â 686 Â 121,B01,1,7,0,2,4,2,1,NaN
378070,202400054402,155 Â 686 Â 123,C01,1,7,0,2,5,2,1,NaN

In [63]:
# On utilise .str.split() puis .str.join('') 
# C'est la méthode la plus fiable : elle découpe par les espaces (peu importe le type) 
# et recolle les morceaux de chiffres immédiatement.

fusion_finale['id_vehicule'] = fusion_finale['id_vehicule'].astype(str).apply(lambda x: "".join(x.split()))

# Vérification immédiate
print("Aperçu du résultat :")
print(fusion_finale['id_vehicule'].head())

Aperçu du résultat :
0    201764
1    201765
2    201762
3    201763
4    201761
Name: id_vehicule, dtype: object

In [64]:
fusion_finale

,Num_Acc,id_vehicule,num_veh,senc,catv,obs,obsm,choc,manv,motor,occutc
0,202100000001,201764,B01,1,1,0,2,1,1,5,NaN
1,202100000001,201765,A01,1,7,0,9,3,17,1,NaN
2,202100000002,201762,A01,0,7,2,2,1,1,0,NaN
3,202100000002,201763,B01,0,7,0,2,1,9,0,NaN
4,202100000003,201761,A01,1,7,0,1,3,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
378066,202400054401,155686119,Y01,1,60,1,2,7,0,5,NaN
378067,202400054401,155686120,A01,1,33,1,2,1,1,1,NaN
378068,202400054402,155686118,A01,1,10,0,2,1,2,1,NaN
378069,202400054402,155686121,B01,1,7,0,2,4,2,1,NaN
378070,202400054402,155686123,C01,1,7,0,2,5,2,1,NaN

In [65]:
# 1. Liste des colonnes à supprimer
colonnes_a_drop = ['senc', 'choc', 'manv', 'occutc']

# 2. On les retire du DataFrame
# errors='ignore' permet d'éviter un plantage si une colonne est déjà absente
fusion_finale = fusion_finale.drop(columns=colonnes_a_drop, errors='ignore')

# 3. Vérification : on affiche les colonnes restantes
print("Colonnes restantes dans le fichier :")
print(fusion_finale.columns.tolist())

# 4. On écrase le fichier pour avoir la version propre
fusion_finale.to_csv('fusion_vehicules_21_24_filtered.csv', index=False, sep=';')

Colonnes restantes dans le fichier :
['Num_Acc', 'id_vehicule', 'num_veh', 'catv', 'obs', 'obsm', 'motor']

In [66]:
fusion_finale

             Num_Acc id_vehicule num_veh catv obs obsm motor
0       202100000001      201764     B01    1   0    2     5
1       202100000001      201765     A01    7   0    9     1
2       202100000002      201762     A01    7   2    2     0
3       202100000002      201763     B01    7   0    2     0
4       202100000003      201761     A01    7   0    1     1
...              ...         ...     ...  ...  ..  ...   ...
378066  202400054401   155686119     Y01   60   1    2     5
378067  202400054401   155686120     A01   33   1    2     1
378068  202400054402   155686118     A01   10   0    2     1
378069  202400054402   155686121     B01    7   0    2     1
378070  202400054402   155686123     C01    7   0    2     1

[378071 rows x 7 columns]

In [70]:
# Chargement du fichier immatriculation 2021
df_imma_2021 = pd.read_csv('projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - véhi imma 2021.csv', sep=';', encoding='latin-1', dtype=str)

In [77]:
# Affiche chaque colonne avec son numéro (index)
for i, col in enumerate(df_imma_2021.columns):
    print(f"Index {i} : {col}")

Index 0 : Id_accident
Index 1 : Lettre Conventionnelle VÃ©hicule
Index 2 : AnnÃ©e
Index 3 : Lieu Admin Actuel - Territoire Nom
Index 4 : Type Accident - LibellÃ© (old)
Index 5 : CNIT
Index 6 : CatÃ©gorie vÃ©hicule
Index 7 : Age vÃ©hicule

In [78]:
# Remplace 0 et le chiffre de l'âge par ceux que tu as vus au-dessus
index_num_acc = 0  
index_age = 7 # <--- CHANGE CE CHIFFRE si l'âge est à un autre index

df_imma_2021_clean = pd.DataFrame()
df_imma_2021_clean['Num_Acc'] = df_imma_2021.iloc[:, index_num_acc]
df_imma_2021_clean['Age_vehicule'] = df_imma_2021.iloc[:, index_age]

# Nettoyage de l'ID
df_imma_2021_clean['Num_Acc'] = df_imma_2021_clean['Num_Acc'].str.replace(r'[^\d]', '', regex=True)

print("Cette fois c'est la bonne :")
print(df_imma_2021_clean.head())

Cette fois c'est la bonne :
  Num_Acc Age_vehicule
0   58720           13
1   58720           12
2   58721           16
3   58722            9
4   58722            1

# nettoyage de immatriculation. Il n'a pas été push pour le moment.

In [86]:


fichiers_verif = {
    '2021': (';', 'projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - véhi imma 2021.csv'),
    '2022': (';', 'projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - véhi imma 2022.csv'),
    '2023': (';', 'projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - véhi imma 2023.csv'),
    '2024': (',', 'projet-groupe-jedha/Dataset/Dataset - Sécurité Routière.xlsx - véhi imma 2024.csv')
}

for annee, (sep, chemin) in fichiers_verif.items():
    df_test = pd.read_csv(chemin, sep=sep, encoding='latin-1', nrows=1)
    print(f"\n--- ANNÉE {annee} ---")
    for i, col in enumerate(df_test.columns):
        print(f"Index {i} : {col}")

--- ANNÉE 2021 ---
Index 0 : Id_accident
Index 1 : Lettre Conventionnelle VÃ©hicule
Index 2 : AnnÃ©e
Index 3 : Lieu Admin Actuel - Territoire Nom
Index 4 : Type Accident - LibellÃ© (old)
Index 5 : CNIT
Index 6 : CatÃ©gorie vÃ©hicule
Index 7 : Age vÃ©hicule

--- ANNÉE 2022 ---
Index 0 : Id_accident
Index 1 : Lettre Conventionnelle VÃ©hicule
Index 2 : AnnÃ©e
Index 3 : Lieu Admin Actuel - Territoire Nom
Index 4 : CNIT
Index 5 : CatÃ©gorie vÃ©hicule
Index 6 : Age vÃ©hicule

--- ANNÉE 2023 ---
Index 0 : Id_accident
Index 1 : Lettre Conventionnelle VÃ©hicule
Index 2 : AnnÃ©e
Index 3 : Lieu Admin Actuel - Territoire Nom
Index 4 : CNIT
Index 5 : CatÃ©gorie vÃ©hicule
Index 6 : Age vÃ©hicule

--- ANNÉE 2024 ---
Index 0 : Id_accident
Index 1 : Lettre Conventionnelle VÃ©hicule
Index 2 : AnnÃ©e
Index 3 : Lieu Admin Actuel - Territoire Nom
Index 4 : CNIT
Index 5 : CatÃ©gorie vÃ©hicule
Index 6 : Age vÃ©hicule

In [87]:
# REMPLACE LES CHIFFRES PAR CEUX QUE TU AS VUS AU DESSUS
config_reelle = {
    '2021': (';', 7), # Si c'est bien 7
    '2022': (';', 6), # À vérifier
    '2023': (';', 6), # À vérifier (L'erreur venait sûrement d'ici !)
    '2024': (',', 6)  # À vérifier
}

liste_imma_clean = []

for annee, (sep, idx_age) in config_reelle.items():
    chemin = fichiers_verif[annee][1]
    df_temp = pd.read_csv(chemin, sep=sep, encoding='latin-1', dtype=str)
    
    df_clean = pd.DataFrame()
    df_clean['Num_Acc'] = df_temp.iloc[:, 0]
    df_clean['Age_vehicule'] = df_temp.iloc[:, idx_age]
    df_clean['Num_Acc'] = df_clean['Num_Acc'].str.replace(r'[^\d]', '', regex=True)
    
    liste_imma_clean.append(df_clean)
    print(f"✅ Année {annee} ok.")

df_age_total = pd.concat(liste_imma_clean, ignore_index=True).drop_duplicates()
print("\nFusion des âges terminée !")

✅ Année 2021 ok.
✅ Année 2022 ok.
✅ Année 2023 ok.
✅ Année 2024 ok.

Fusion des âges terminée !

In [88]:
df_age_total

         Num_Acc Age_vehicule
0          58720           13
1          58720           12
2          58721           16
3          58722            9
4          58722            1
...          ...          ...
344407  67286660            7
344408  67286661            7
344409  67286662           14
344410  67286663            8
344411  67286663          NaN

[334517 rows x 2 columns]

In [89]:
# 1. On fusionne la table des âges avec ton DataFrame principal
# On utilise Num_Acc comme clé commune
fusion_finale = pd.merge(fusion_finale, df_age_total, on='Num_Acc', how='left')

# 2. Petite vérification pour s'assurer qu'on n'a pas créé de doublons de lignes
print(f"Nombre de lignes final : {len(fusion_finale)}")

# 3. Aperçu pour admirer le résultat
print("\nAperçu des colonnes et de l'âge :")
print(fusion_finale[['Num_Acc', 'id_vehicule', 'Age_vehicule']].head())

# 4. Sauvegarde finale en CSV pour ne plus avoir à refaire tout ça !
fusion_finale.to_csv('base_routiere_complete_21_24.csv', index=False, sep=';')
print("\nFichier sauvegardé sous 'base_routiere_complete_21_24.csv'")

Nombre de lignes final : 378071

Aperçu des colonnes et de l'âge :
        Num_Acc id_vehicule Age_vehicule
0  202100000001      201764          NaN
1  202100000001      201765          NaN
2  202100000002      201762          NaN
3  202100000002      201763          NaN
4  202100000003      201761          NaN

Fichier sauvegardé sous 'base_routiere_complete_21_24.csv'

In [90]:
fusion_finale

             Num_Acc id_vehicule num_veh catv obs obsm motor Age_vehicule
0       202100000001      201764     B01    1   0    2     5          NaN
1       202100000001      201765     A01    7   0    9     1          NaN
2       202100000002      201762     A01    7   2    2     0          NaN
3       202100000002      201763     B01    7   0    2     0          NaN
4       202100000003      201761     A01    7   0    1     1          NaN
...              ...         ...     ...  ...  ..  ...   ...          ...
378066  202400054401   155686119     Y01   60   1    2     5          NaN
378067  202400054401   155686120     A01   33   1    2     1          NaN
378068  202400054402   155686118     A01   10   0    2     1          NaN
378069  202400054402   155686121     B01    7   0    2     1          NaN
378070  202400054402   155686123     C01    7   0    2     1          NaN

[378071 rows x 8 columns]

In [91]:
fusion_finale

             Num_Acc id_vehicule num_veh catv obs obsm motor Age_vehicule
0       202100000001      201764     B01    1   0    2     5          NaN
1       202100000001      201765     A01    7   0    9     1          NaN
2       202100000002      201762     A01    7   2    2     0          NaN
3       202100000002      201763     B01    7   0    2     0          NaN
4       202100000003      201761     A01    7   0    1     1          NaN
...              ...         ...     ...  ...  ..  ...   ...          ...
378066  202400054401   155686119     Y01   60   1    2     5          NaN
378067  202400054401   155686120     A01   33   1    2     1          NaN
378068  202400054402   155686118     A01   10   0    2     1          NaN
378069  202400054402   155686121     B01    7   0    2     1          NaN
378070  202400054402   155686123     C01    7   0    2     1          NaN

[378071 rows x 8 columns]

In [92]:
# Renommage des colonnes pour plus de clarté
fusion_finale = fusion_finale.rename(columns={
    'catv': 'categorie_vehicule',
    'obs': 'obstacle_fixe',
    'obsm': 'obstacle_mobile',
    'motor': 'motorisation'
})

# Vérification du résultat
print("Nouveaux noms de colonnes :")
print(fusion_finale[['categorie_vehicule', 'obstacle_fixe', 'obstacle_mobile', 'motorisation']].head())

Nouveaux noms de colonnes :
  categorie_vehicule obstacle_fixe obstacle_mobile motorisation
0                  1             0               2            5
1                  7             0               9            1
2                  7             2               2            0
3                  7             0               2            0
4                  7             0               1            1

In [93]:
fusion_finale

,Num_Acc,id_vehicule,num_veh,categorie_vehicule,obstacle_fixe,obstacle_mobile,motorisation,Age_vehicule
0,202100000001,201764,B01,1,0,2,5,NaN
1,202100000001,201765,A01,7,0,9,1,NaN
2,202100000002,201762,A01,7,2,2,0,NaN
3,202100000002,201763,B01,7,0,2,0,NaN
4,202100000003,201761,A01,7,0,1,1,NaN
...,...,...,...,...,...,...,...,...
378066,202400054401,155686119,Y01,60,1,2,5,NaN
378067,202400054401,155686120,A01,33,1,2,1,NaN
378068,202400054402,155686118,A01,10,0,2,1,NaN
378069,202400054402,155686121,B01,7,0,2,1,NaN
378070,202400054402,155686123,C01,7,0,2,1,NaN

In [94]:
fusion_finale = fusion_finale.drop(columns="Age_vehicule")

In [95]:
fusion_finale

,Num_Acc,id_vehicule,num_veh,categorie_vehicule,obstacle_fixe,obstacle_mobile,motorisation
0,202100000001,201764,B01,1,0,2,5
1,202100000001,201765,A01,7,0,9,1
2,202100000002,201762,A01,7,2,2,0
3,202100000002,201763,B01,7,0,2,0
4,202100000003,201761,A01,7,0,1,1
...,...,...,...,...,...,...,...
378066,202400054401,155686119,Y01,60,1,2,5
378067,202400054401,155686120,A01,33,1,2,1
378068,202400054402,155686118,A01,10,0,2,1
378069,202400054402,155686121,B01,7,0,2,1
378070,202400054402,155686123,C01,7,0,2,1

In [96]:
# Sauvegarde du DataFrame fusion_finale
fusion_finale.to_csv('base_routiere_propre.csv', index=False, sep=';', encoding='utf-8-sig')

print("Fichier sauvegardé avec succès sous le nom 'base_routiere_propre.csv'")

Fichier sauvegardé avec succès sous le nom 'base_routiere_propre.csv'

Num_Acc               0
id_vehicule           0
num_veh               0
categorie_vehicule    0
obstacle_fixe         0
obstacle_mobile       0
motorisation          0
dtype: int64